# Generated by Django 5.1.4 on 2024-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=512),
            preserve_default=False,
        ),
    ]
