# Generated by Django 5.1.3 on 2024-12-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_file_remove_task_user_task_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
