# Generated by Django 5.1.3 on 2024-12-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_reminder_options_reminder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
