# Generated by Django 5.1.3 on 2024-12-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_reminder_modified_at_alter_task_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
