# Generated by Django 5.1.3 on 2024-12-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_task_reminder_time_delete_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='on_delete',
            new_name='is_delete',
        ),
    ]
